# 1. Build Stage: Compila il codice Angular con Node.js
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
# Genera i file statici (HTML/JS/CSS) nella cartella dist/frontend/browser
RUN npm run build --configuration=production

# 2. Run Stage: Serve i file statici con Nginx
FROM nginx:alpine
# Copia i file compilati dalla cartella di build a quella di Nginx
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
# Copia la configurazione custom di Nginx (per gestire il routing di Angular)
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80