services:
  # 1. Database PostgreSQL
  postgres:
    image: postgres:16
    container_name: bugboard-db
    environment:
      POSTGRES_DB: bugboard_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Frontend Angular (sviluppo)
  frontend:
    image: node:20-alpine
    container_name: bugboard-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
# Aggiungi l'installazione globale di @angular/cli prima di avviare
    command: sh -c "npm install -g @angular/cli@18 && npm install && ng serve --host 0.0.0.0 --poll 2000 --disable-host-check"
    ports:
      - "4200:4200"
    depends_on:
      - postgres

volumes:
  postgres_data: